name: Nuget Publish

on:
  release:
    types: [published]
    paths:
      - "**"

jobs:
  version:
    name: Nuget Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Build Package
        run: dotnet pack --output nupkgs
      - name: Push to Nuget
        run: dotnet nuget push "./bin/Release/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate

